DOMAIN = "ble_device_manager"
CONF_IGNORED_DEVICES = "ignored_devices"
CONF_MONITORED_DEVICES = "monitored_devices"
CONF_NAME = "name"
CONF_ADDRESS = "address"
CONF_THRESHOLD = "threshold"
CONF_IGNORE = "ignore"
DEFAULT_SCAN_INTERVAL = 300  # 5 minuti in secondi
DEFAULT_BATTERY_THRESHOLD = 30